# Generated by Django 6.0.3 on 2026-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('prize', models.IntegerField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos')),
            ],
        ),
    ]
